/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAdminHeader: typeof import('./src/components/AppAdminHeader.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppHeader2: typeof import('./src/components/AppHeader2.vue')['default']
    AppMap: typeof import('./src/components/AppMap.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroImage: typeof import('./src/components/HeroImage.vue')['default']
    ListServices: typeof import('./src/components/ListServices.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    Testemonials: typeof import('./src/components/Testemonials.vue')['default']
  }
}
